name: Docker Image CI
on:
  push:
    branches:
      - master  # Exécuter le pipeline sur chaque push dans masterr

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_OWNER: ghoulfatma

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build & Push Frontend
      uses: docker/build-push-action@v5
      with:
        context: ./Front
        push: true
        tags: ${{ env.IMAGE_OWNER }}/frontend:latest

    - name: Build & Push Web API
      uses: docker/build-push-action@v5
      with:

        context: ./Docvision/Docvision
        push: true
        tags: ${{ env.IMAGE_OWNER }}/web-api:latest

    - name: Build & Push PDF API
      uses: docker/build-push-action@v5
      with:
        context: ./pdf_api
        push: true
        tags: ${{ env.IMAGE_OWNER }}/pdf-api:latest

    - name: Build & Push Ollama
      uses: docker/build-push-action@v5
      with:
        context: ./ollama
        push: true
        tags: ${{ env.IMAGE_OWNER }}/ollama:latest
